# Copyright (c) 2023-2025, MLSysOps Consortium
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

site_name: MLSysOps framework
site_url: https://mlsysops-eu.github.io/mlsysops-framework
site_author: MLSysOps Consortium

repo_url: https://github.com/mlsysops-eu/mlsysops-framework
repo_name: mlsysops-eu/mlsysops-framework

# We use a custom `copyright` plugin, so only set the starting year
copyright: "2023"

not_in_nav: /index.md

draft_docs: |
  performance/
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Installation: installation.md
  - Design:
      - design/*.md
  - MLConnector:
      - mlconnector/Overview.md
      - mlconnector/Installation.md
      - mlconnector/Step-by-step guide.md
  - Developer Guide: 
      - developer-guide/*.md
  - Tutorials:
      - tutorials/*.md

theme:
  name: material
  favicon: assets/img/mlsysops-logo.png
  logo: assets/img/mlsysops-logo.png
  custom_dir: docs/overrides
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: vaccel
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode


  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.suggest
    - search.share

extra_css:
  - assets/stylesheets/theme.css
extra_javascript:
  - assets/javascripts/console-copy.js

extra:
  version:
    provider: mike
    alias: true
  analytics:
    provider: google
    property: G-X2S0PFR6ZY
  gen_py_reference:
    out_path: language-bindings/python-bindings/api-reference

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: '🔗'
      toc_depth: 3
  - pymdownx.blocks.tab:
      alternate_style: True
      combine_header_slug: True
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        # exclude '$' from copying
        - name: console
          class: console
          validator: ^.*
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - section-index
  - awesome-nav
  - macros:
      include_yaml: [variables/versions.yml]
      j2_block_start_string: "[%"
      j2_block_end_string: "%]"
      j2_variable_start_string: "[["
      j2_variable_end_string: "]]"
      j2_comment_start_string: '[#'
      j2_comment_end_string: '#]'
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
      css_files:
          - assets/stylesheets/theme.css
      js_files:
          - assets/javascripts/console-copy.js
  - autorefs

hooks:
  - docs/hooks/copyright.py

