mechanisms:
- "fluidity"
default_telemetry_metrics: "None"
policy_directory: "policies"
mechanisms_directory: "mechanisms"

continuum_layer: "cluster"
monitor_data_retention_time: 30
node_exporter_scrape_interval: 10s
managed_telemetry_enabled: true