apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlsysops-agents-sa
  namespace: mlsysops-framework
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlsysops-agents-sa
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mlsysops-framework-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["*"]
- apiGroups: ["node.k8s.io"]
  resources: ["runtimeclasses"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["mlsysops.eu"]
  resources: ["mlsysopsnodes", "mlsysopsapps", "mlsysopscontinuums", "mlsysopsdatacenters","mlsysopsclusters"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mlsysops-framework-rb
  namespace: mlsysops-framework  # Role binding applies to 'mlsysops-framework'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mlsysops-framework-role
subjects:
- kind: ServiceAccount
  name: mlsysops-agents-sa
  namespace: mlsysops-framework
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-rb
  namespace: default  # Role binding applies to 'default' namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mlsysops-framework-role
subjects:
- kind: ServiceAccount
  name: mlsysops-agents-sa
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mlsysops-framework-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mlsysops-framework-role
subjects:
- kind: ServiceAccount
  name: mlsysops-agents-sa
  namespace: mlsysops-framework
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mlsysops-framework-role
subjects:
- kind: ServiceAccount
  name: mlsysops-agents-sa
  namespace: default
---