---
# DaemonSet for Node Agent
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mlsysops-node-agent
  namespace: mlsysops-framework
spec:
  selector:
    matchLabels:
      app: node-agent
  template:
    metadata:
      labels:
        app: node-agent
    spec:
      # Use nodeSelector to target nodes with mlsysops/continuumLayer=node
      nodeSelector:
        mlsysops/continuumLayer: "node"
      containers:
        - name: node-agent
          image: registry.mlsysops.eu/agent/agents/node:0.0.15
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLUSTER_NAME
              value: mls-ubiw-1
            - name: EJABBERD_DOMAIN
              value: karmada.mlsysops.eu
            - name: NODE_PASSWORD
              value: "1234"
            - name: CONFIG_PATH
              value: "/etc/mlsysops.conf/$(NODE_NAME).yaml"
            - name: DESCRIPTION_PATH
              value: "/etc/mlsysops.desc"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: node-config-volume
              mountPath: /etc/mlsysops.conf
            - name: description-volume
              mountPath: /etc/mlsysops.desc
      volumes:
        - name: node-config-volume
          configMap:
            name: node-agent-config
        - name: description-volume
          configMap:
            name: node-descriptions
