# generated by datamodel-codegen:
#   filename:  tmpy427nwqa_schema.json
#   timestamp: 2025-12-17T13:09:15+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class ClusterPlacement(BaseModel):
    cluster_id: Optional[List[str]] = Field(
        None, description='Array of clusters that can host the application.'
    )


class Metadata(BaseModel):
    name: Optional[str] = Field(None, description='The unique name of the component')
    uid: Optional[str] = Field(
        None,
        description='The unique identifier of the component (not given by app provider).',
    )


class ContinuumLayerEnum(Enum):
    cloud = 'cloud'
    far_edge = 'far_edge'
    edge_infrastructure = 'edge_infrastructure'
    edge = 'edge'
    field_ = '*'


class NodePlacement(BaseModel):
    continuum_layer: Optional[List[ContinuumLayerEnum]] = None
    mobile: Optional[bool] = Field(
        None,
        description='Specify if the component needs to be deployed on a mobile node (optional)',
    )
    labels: Optional[List[str]] = Field(
        None, description='The required labels for filtering.'
    )
    node: Optional[str] = Field(
        None,
        description='The required node name to be the host of the component (optional).',
    )


class Model(Enum):
    d455 = 'd455'
    imx477 = 'imx477'
    picamera_v2 = 'picamera-v2'


class CameraType(Enum):
    rgb = 'rgb'
    nir = 'nir'
    thermal = 'thermal'
    monocular = 'monocular'


class Resolution(Enum):
    field_1024x768 = '1024x768'
    field_4056x3040 = '4056x3040'


class Camera(BaseModel):
    model: Optional[Model] = Field(
        None, description='The model name of the camera sensor'
    )
    camera_type: Optional[CameraType] = Field(
        None, description='The camera sensor type.'
    )
    minimum_framerate: Optional[int] = None
    resolution: Optional[Resolution] = None


class Model1(Enum):
    sdc30 = 'sdc30'
    ds18b20 = 'ds18b20'


class Temperature(BaseModel):
    model: Optional[Model1] = Field(
        None, description='The model name of the temperature sensor'
    )


class Sensor(BaseModel):
    camera: Optional[Camera] = None
    temperature: Optional[Temperature] = None


class Relation(Enum):
    lower_or_equal = 'lower_or_equal'
    greater_or_equal = 'greater_or_equal'
    equal = 'equal'
    lower_than = 'lower_than'
    greater_than = 'greater_than'


class QosMetric(BaseModel):
    application_metric_id: Optional[str] = Field(None, description='App metric id.')
    target: Optional[float] = None
    relation: Optional[Relation] = None


class RuntimeClassName(Enum):
    nvidia = 'nvidia'
    default = 'default'
    kata_fc = 'kata-fc'
    kata_dragon = 'kata-dragon'
    urunc = 'urunc'
    crun = 'crun'
    lunatic = 'lunatic'
    nvidia_experimental = 'nvidia-experimental'
    spin = 'spin'
    wasmedge = 'wasmedge'
    slight = 'slight'
    runc = 'runc'


class RestartPolicy(Enum):
    Always = 'Always'
    OnFailure = 'OnFailure'
    Never = 'Never'


class Os(Enum):
    ubuntu = 'ubuntu'
    kali = 'kali'
    zephyr = 'zephyr'


class NodeType(Enum):
    virtualized = 'virtualized'
    native = 'native'
    bare_metal = 'bare_metal'


class ContainerRuntime(Enum):
    containerd = 'containerd'
    docker = 'docker'
    embserve = 'embserve'
    kata = 'kata'
    kata_qemu = 'kata-qemu'
    kata_clh = 'kata-clh'
    kata_fc = 'kata-fc'
    urunc = 'urunc'
    nvidia = 'nvidia'


class ImagePullPolicy(Enum):
    Always = 'Always'
    Never = 'Never'
    IfNotPresent = 'IfNotPresent'


class ArchitectureEnum(Enum):
    arm64 = 'arm64'
    amd64 = 'amd64'
    arm_v7 = 'arm-v7'
    arm_v8 = 'arm-v8'


class Cpu(BaseModel):
    requests: Optional[str] = None
    limits: Optional[str] = None
    architecture: Optional[List[ArchitectureEnum]] = None
    frequency: Optional[float] = Field(None, description='required frequency in Hz.')
    performance_indicator: Optional[float] = Field(
        None,
        description='This field assists MLSysOps with an initial hint in order to filter out nodes based on their performance capabilities.',
    )


class Memory(BaseModel):
    requests: Optional[str] = None
    limits: Optional[str] = None


class Model2(Enum):
    k80 = 'k80'
    k40 = 'k40'


class Gpu(BaseModel):
    model: Optional[Model2] = None
    memory: Optional[str] = None
    performance_indicator: Optional[float] = Field(
        None,
        description='This field assists MLSysOps with an initial hint in order to filter out nodes based on their performance capabilities.',
    )


class PlatformRequirements(BaseModel):
    cpu: Optional[Cpu] = None
    memory: Optional[Memory] = None
    disk: Optional[str] = Field(None, description='required Disk space (in GB).')
    gpu: Optional[Gpu] = None


class Protocol(Enum):
    UDP = 'UDP'
    TCP = 'TCP'
    SCTP = 'SCTP'


class Port(BaseModel):
    container_port: Optional[int] = Field(
        None,
        description="Number of port to expose on the component's IP address. This must be a valid port number, 0 < x < 65536.",
    )
    protocol: Optional[Protocol] = Field(
        None, description='Protocol for port. Defaults to "TCP".'
    )


class FieldRef(BaseModel):
    field_path: Optional[str] = None


class ValueFrom(BaseModel):
    field_ref: Optional[FieldRef] = None


class EnvItem(BaseModel):
    name: Optional[str] = Field(None, description='Name of the environment variable.')
    value_from: Optional[ValueFrom] = None
    value: Optional[str] = Field(None, description='Value of the environment variable.')


class Container(BaseModel):
    image: Optional[str] = Field(None, description='The name of the container image.')
    command: Optional[List[str]] = None
    image_pull_policy: Optional[ImagePullPolicy] = Field(
        None,
        description='Image pull policy. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise.',
    )
    platform_requirements: Optional[PlatformRequirements] = Field(
        None, description='The resource requirements of the container.'
    )
    ports: Optional[List[Port]] = Field(
        None, description='Environment variables for the container.'
    )
    env: Optional[List[EnvItem]] = Field(
        None, description='Environment variables for the container.'
    )


class Component(BaseModel):
    metadata: Metadata
    node_placement: Optional[NodePlacement] = None
    sensors: Optional[List[Sensor]] = None
    qos_metrics: Optional[List[QosMetric]] = None
    host_network: Optional[bool] = Field(
        None,
        description="Host networking requested for this component. Use the host's network namespace. If this option is set, the ports that will be used must be specified. Default to false.",
    )
    runtime_class_name: Optional[RuntimeClassName] = None
    restart_policy: Optional[RestartPolicy] = Field(
        None, description='Restart policy for the container. Default to Always.'
    )
    os: Optional[Os] = None
    node_type: Optional[NodeType] = None
    container_runtime: Optional[ContainerRuntime] = None
    containers: List[Container]


class Type(Enum):
    ingress = 'ingress'
    egress = 'egress'


class ComponentInteraction(BaseModel):
    component_name1: Optional[str] = Field(None, description='The "source" component.')
    type: Optional[Type] = None
    component_name2: Optional[str] = Field(
        None, description='The "destination" component.'
    )


class Relation1(Enum):
    greater_or_equal = 'greater_or_equal'
    equal = 'equal'
    greater_than = 'greater_than'


class AchievementWeight(BaseModel):
    metric_id: Optional[str] = None
    weight: Optional[float] = None


class GlobalSatisfaction(BaseModel):
    threshold: Optional[float] = Field(
        None, description='Happiness minimum required value (range (0-1])'
    )
    relation: Optional[Relation1] = None
    achievement_weights: Optional[List[AchievementWeight]] = None


class MLSysOpsApp(BaseModel):
    name: Optional[str] = Field(None, description='The application name.')
    cluster_placement: Optional[ClusterPlacement] = None
    components: List[Component]
    component_interactions: Optional[List[ComponentInteraction]] = None
    global_satisfaction: Optional[GlobalSatisfaction] = None


class MlsysopsappSchema(BaseModel):
    MLSysOpsApp: MLSysOpsApp
