apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejabberd
  namespace: mlsysops-framework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ejabberd
  template:
    metadata:
      labels:
        app: ejabberd
    spec:
      containers:
      - name: ejabberd
        image: ghcr.io/processone/ejabberd:latest
        ports:
          - containerPort: 5222
            hostPort: 5222
            protocol: "TCP"
          - containerPort: 5280
            hostPort: 5280
            protocol: "TCP"
        env:
        - name: POD_IP
          value: karmada.mlsysops.eu
#          valueFrom:
#            fieldRef:
#              fieldPath: status.hostIP
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "📥 Generating ejabberd.yml with pod IP = ${POD_IP}" && \
            sed "s/__POD_IP__/${POD_IP}/g" /config/ejabberd.yml.template \
              > /opt/ejabberd/conf/ejabberd.yml && \
            echo "✅ Starting ejabberd..." && \
            exec ejabberdctl foreground
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: ejabberd-config
