apiVersion: v1
kind: Service
metadata:
  name: ejabberd
  namespace: mlsysops-framework
spec:
  selector:
    app: ejabberd
  ports:
    - name: xmpp
      port: 5222
      targetPort: 5222
    - name: web
      port: 5280
      targetPort: 5280
  type: NodePort
