[default]
extend-ignore-re = [
  "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
  "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on"
]

[default.extend-words]
SEH = "SEH"
ser = "ser"
nd = "nd"

[files]
extend-exclude = [
  "subprojects/*",
]
