apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ name }}
spec:
  resourceSelectors:
    - apiVersion: mlsysops.eu/v1
      kind: MLSysOpsApp
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      namespace: mlsysops-framework
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      namespace: default
  conflictResolution: Overwrite
  placement:
    clusterAffinity:
      clusterNames:
        {% for cluster in cluster_names %}
        - {{ cluster }}
        {% endfor %}

