apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: {{ name }}
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: mlsysopsapps.mlsysops.eu
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: mlsysopsnodes.mlsysops.eu
  placement:
    clusterAffinity:
      clusterNames:
        {% for cluster in cluster_names %}
        - {{ cluster }}
        {% endfor %}

