apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: {{ name }}
spec:
  targetCluster:
    clusterNames:
        {% for cluster in cluster_names %}
        - {{ cluster }}
        {% endfor %}
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
    - apiVersion: v1
      kind: Node
    - apiVersion: v1
      kind: Service