apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: proxy-resources
spec:
  targetCluster:
    clusterNames:
      - uth-prod-cluster
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
    - apiVersion: v1
      kind: Node
    - apiVersion: v1
      kind: Service