# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mlsysops-framework

---
# DaemonSet for Node Agent
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mlsysops-node-agent
  namespace: mlsysops-framework
spec:
  selector:
    matchLabels:
      app: node-agent
  template:
    metadata:
      labels:
        app: node-agent
    spec:
      # Use nodeSelector to target nodes with mlsysops/continuumLayer=node
      nodeSelector:
        mlsysops/continuumLayer: "node"
      containers:
        - name: node-agent
          image: registry.mlsysops.eu/agent/agents/node:0.0.2
          env:
            - name: KUBECONFIG
              value: uthprod.kubeconfig
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLUSTER_NAME
              value: cluster
            - name: EJABBERD_DOMAIN
              value: karmada.mlsysops.eu
            - name: NODE_PASSWORD
              value: "1234"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

---
# DaemonSet for Cluster Agent
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mlsysops-cluster-agent
  namespace: mlsysops-framework
spec:
  selector:
    matchLabels:
      app: cluster-agent
  template:
    metadata:
      labels:
        app: cluster-agent
    spec:
      # Use nodeSelector to target nodes with mlsysops/continuumLayer=cluster
      nodeSelector:
        mlsysops/continuumLayer: "cluster"
      containers:
        - name: cluster-agent
          image: registry.mlsysops.eu/agent/agents/cluster:0.0.2
          env:
            - name: KUBECONFIG
              value: uthprod.kubeconfig
            - name: NODE_NAME
              value: cluster1
            - name: CLUSTER_NAME
              value: cluster
            - name: EJABBERD_DOMAIN
              value: karmada.mlsysops.eu
            - name: NODE_PASSWORD
              value: "1234"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---

# DaemonSet for continuum Agent
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mlsysops-continuum-agent
  namespace: mlsysops-framework
spec:
  selector:
    matchLabels:
      app: continuum-agent
  template:
    metadata:
      labels:
        app: continuum-agent
    spec:
      # Use nodeSelector to target nodes with mlsysops/continuumLayer=continuum
      nodeSelector:
        mlsysops/continuumLayer: "continuum"
      containers:
        - name: continuum-agent
          image: registry.mlsysops.eu/agent/agents/continuum:0.0.2
          env:
            - name: KUBECONFIG
              value: uthprod.kubeconfig
            - name: NODE_NAME
              value: cluster1
            - name: CLUSTER_NAME
              value: cluster
            - name: EJABBERD_DOMAIN
              value: karmada.mlsysops.eu
            - name: NODE_PASSWORD
              value: "1234"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"