# DaemonSet for Cluster Agent
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mlsysops-cluster-agent
  namespace: mlsysops-framework
spec:
  selector:
    matchLabels:
      app: cluster-agent
  template:
    metadata:
      labels:
        app: cluster-agent
    spec:
      serviceAccountName: mlsysops-agents-sa
      # Use nodeSelector to target nodes with mlsysops/continuumLayer=cluster
      nodeSelector:
        mlsysops/continuumLayer: "cluster"
      containers:
        - name: cluster-agent
          image: registry.mlsysops.eu/agent/agents/cluster:0.0.15
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: REDIS_HOST
              value: karmada.mlsysops.eu
            - name: CLUSTER_NAME
              value: uth-karmada
            - name: EJABBERD_DOMAIN
              value: karmada.mlsysops.eu
            - name: NODE_PASSWORD
              value: "1234"
            - name: PYTHONPATH
              value: "/workdir/fluidity"
            - name: CONFIG_PATH
              value: "/etc/mlsysops.conf/cluster-config.yaml"
            - name: DESCRIPTION_PATH
              value: "/etc/mlsysops.desc"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: description-volume
              mountPath: /etc/mlsysops.desc
            - name: cluster-config-volume
              mountPath: /etc/mlsysops.conf
            - name: policies-volume
              mountPath: /etc/mlsysops/policies
      volumes:
        - name: cluster-config-volume
          configMap:
            name: cluster-agent-config
        - name: description-volume
          configMap:
            name: system-description
        - name: policies-volume
          configMap:
            name: cluster-policies
