apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlsysops-agents-sa
  namespace: mlsysops-framework
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mlsysops-framework-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]
- apiGroups: ["node.k8s.io"]
  resources: ["runtimeclasses"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["fluidity.gr"]  # Added API group for mlsysopsnodes
  resources: ["mlsysopsnodes", "mlsysopsapps"]  # Added resource
  verbs: ["*"]  # Added wildcard to grant all permissions
- apiGroups: [""]
  resources: ["pods"]  # Added rule for 'pods'
  verbs: ["*"]  # Granting all permissions for 'pods'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mlsysops-framework-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mlsysops-framework-role
subjects:
- kind: ServiceAccount
  name: mlsysops-agents-sa
  namespace: mlsysops-framework
---