  mechanisms:
    - "CPUFrequencyConfigurator"
    - "fluidity_proxy"
  default_telemetry_metrics: "None"
  policy_directory: "policies"
  mechanisms_directory: "mechanisms"
  continuum_layer: "node"
  monitor_data_retention_time: 30
  node_exporter_scrape_interval: 10s
  node_description: descriptions/csl-rpi5-1
  managed_telemetry_enabled: true

  behaviours:
      APIPingBehaviour:
          enabled: False
      Check_ml_deployment_Behaviour: # This is oneshot behaviour should be False always
          enabled: False
      CheckInactiveClustersBehaviour:
          enabled: False
          period: 10
      HBReceiverBehaviour:
          enabled: True
      HeartbeatBehaviour:
          enabled: False
          period: 10  # Example parameter for PeriodicBehaviour
      ManagementModeBehaviour:
          enabled: False
      ManageSubscriptionBehaviour:
          enabled: False
      Subscribe:
          enabled: True
