apiVersion: mlsysops.eu/v1
kind: MLSysOpsApp
metadata:
  name: toy-app
clusterPlacement:
  clusterID: 
    # Add the cluster name from kubeconfig
    - "uth-prod-cluster"
  instances: 1
components: 
  - Component:
      name: image-checker
    nodePlacement:
      continuumLayer: 
        - Edge
        - Cloud
      node: csl-jetson1
      labels:
        - "node-type:cloud"
      Scaling:
        scalingMode: manual
        instances: 1
    restartPolicy: OnFailure
    containers:
      # ADD YOUR CONTAINER IMAGE 
      - image: registry.mlsysops.eu/toycase/demo2025/camera:0.3.2
        imagePullPolicy: IfNotPresent
