services:
  continuum_agent:
    image: registry.mlsysops.eu/agent/agents/continuum:0.0.0
    network_mode: host
    environment:
      KUBECONFIG: uthprod.kubeconfig
      NODE_NAME: karmada
      CLUSTER_NAME: cluster
      EJABBERD_DOMAIN: karmada.mlsysops.eu
      NODE_PASSWORD: 1234

  cluster_agent:
    image: registry.mlsysops.eu/agent/agents/cluster:0.0.0
    network_mode: host
    environment:
      KUBECONFIG: uthprod.kubeconfig
      NODE_NAME: cluster1
      CLUSTER_NAME: cluster
      EJABBERD_DOMAIN: karmada.mlsysops.eu
      NODE_PASSWORD: 1234
      PYTHONPATH: "/workdir:/workdir/fluidity"

  node_agent:
    image: registry.mlsysops.eu/agent/agents/node:0.0.0
    network_mode: host
    environment:
      NODE_NAME: csl-rpi5-1
      CLUSTER_NAME: cluster
      EJABBERD_DOMAIN: karmada.mlsysops.eu
      NODE_PASSWORD: 1234