MLSysOpsApplication:
  name: uth-demo-app
  clusterPlacement:
    clusterID: 
      - "uth-prod-cluster"
    instances: 1
  components: 
    - Component:
        name: camera-app
      nodePlacement:
        continuumLayer: Edge
        node: node1
        labels:
          - "node-type:edge"
        Scaling:
          scalingMode: manual
          instances: 1
      restartPolicy: OnFailure
      containers:
        - image: registry.mlsysops.eu/toycase/demo2025/camera:0.2.6
          imagePullPolicy: IfNotPresent
    - Component:
        name: detector-app
      nodePlacement:
        continuumLayer: Edge
        node: node1
        labels:
          - "node-type:edge"
        Scaling:
          scalingMode: manual
          instances: 1
      restartPolicy: OnFailure
      containers:
        - image: registry.mlsysops.eu/toycase/demo2025/detector:0.2.6
          imagePullPolicy: IfNotPresent
    - Component:
        name: classifier-app
      nodePlacement:
        continuumLayer: Cloud
        node: node1
        labels:
          - "node-type:cloud"
        Scaling:
          scalingMode: manual
          instances: 1
      restartPolicy: OnFailure
      containers:
        - image: registry.mlsysops.eu/toycase/demo2025/classifier:test
          imagePullPolicy: IfNotPresent
          # ports:
          #   - containerPort: 5006
          #     protocol: UDP
  componentInteractions:
    - componentName1: camera-app
      interactionType: egress
      componentName2: detector-app
    - componentName1: detector-app
      interactionType: egress
      componentName2: classifier-app
