nav:
  - Home: index.md
  - Getting Started: 
      - Testbed Setup: testbed.md
      - Quickstart: quickstart.md
  - Installation: installation.md
  - Design:
      - design/*.md
  - MLConnector:
      - mlconnector/Overview.md
      - mlconnector/Installation.md
      - mlconnector/Step-by-step guide.md
  - Developer Guide: 
      - developer-guide/*.md
  - Tutorials:
      - tutorials/*.md


